#!/bin/bash

# DTC Logbook - Quick Render Setup Script
# This script helps you prepare your app for Render deployment

set -e

echo "================================"
echo "DTC Logbook - Render Setup Guide"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Prerequisites Check${NC}"
echo "================================"

# Check PHP version
PHP_VERSION=$(php -v | grep -oP 'PHP \K[0-9]+\.[0-9]+' | head -1)
MIN_PHP="8.2"

if (( $(echo "$PHP_VERSION >= $MIN_PHP" | bc -l) )); then
    echo -e "${GREEN}✓ PHP $PHP_VERSION is compatible${NC}"
else
    echo -e "${YELLOW}⚠ PHP $PHP_VERSION detected. Render requires PHP 8.2+${NC}"
fi

# Check Composer
if command -v composer &> /dev/null; then
    echo -e "${GREEN}✓ Composer is installed${NC}"
else
    echo -e "${YELLOW}⚠ Composer not found. Install from https://getcomposer.org${NC}"
fi

# Check Node.js
if command -v npm &> /dev/null; then
    echo -e "${GREEN}✓ Node.js is installed${NC}"
else
    echo -e "${YELLOW}⚠ Node.js not found. Install from https://nodejs.org${NC}"
fi

# Check Git
if command -v git &> /dev/null; then
    echo -e "${GREEN}✓ Git is installed${NC}"
else
    echo -e "${YELLOW}⚠ Git not found. Install from https://git-scm.com${NC}"
fi

echo ""
echo -e "${BLUE}Step 2: Verify Configuration Files${NC}"
echo "================================"

FILES=(
    "render.yaml:Render configuration"
    "Procfile:Process file for deployment"
    ".env.example:Environment template"
    "RENDER_SETUP.md:Render deployment guide"
    "SECURITY.md:Security guidelines"
)

for file_info in "${FILES[@]}"; do
    IFS=':' read -r file description <<< "$file_info"
    if [ -f "$file" ]; then
        echo -e "${GREEN}✓ $file - $description${NC}"
    else
        echo -e "${YELLOW}⚠ $file not found${NC}"
    fi
done

echo ""
echo -e "${BLUE}Step 3: Local Testing (Optional)${NC}"
echo "================================"
echo ""
read -p "Run local tests before deployment? (y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Installing dependencies..."
    composer install 2>/dev/null || true
    npm install 2>/dev/null || true
    
    echo "Running security audit..."
    composer audit --format=compact 2>/dev/null || echo "No vulnerabilities found"
    npm audit --audit-level=moderate 2>/dev/null || echo "Check npm audit results"
    
    echo -e "${GREEN}✓ Security audit complete${NC}"
fi

echo ""
echo -e "${BLUE}Step 4: Git Preparation${NC}"
echo "================================"

# Check if .env is in .gitignore
if grep -q "^\.env" .gitignore; then
    echo -e "${GREEN}✓ .env is properly ignored in .gitignore${NC}"
else
    echo -e "${YELLOW}⚠ Check that .env is in .gitignore${NC}"
fi

# Check for uncommitted .env
if git ls-files --others --exclude-standard | grep -q "\.env"; then
    echo -e "${YELLOW}⚠ Untracked .env file detected${NC}"
    echo "  Make sure .env is NOT committed to git"
fi

echo ""
echo -e "${BLUE}Step 5: Render Environment Variables${NC}"
echo "================================"
echo ""
echo "You need to set these environment variables on Render:"
echo ""
echo "Required:"
echo "  • APP_ENV=production"
echo "  • APP_KEY=<auto-generated>"
echo "  • JWT_SECRET=<auto-generated>"
echo "  • DB_CONNECTION=pgsql"
echo "  • DB_HOST=<your-render-database-host>"
echo "  • DB_PORT=5432"
echo "  • DB_DATABASE=postgres"
echo "  • DB_USERNAME=<your-username>"
echo "  • DB_PASSWORD=<your-password>"
echo ""
echo "For Email (Gmail example):"
echo "  • PHPMAILER_HOST=smtp.gmail.com"
echo "  • PHPMAILER_PORT=587"
echo "  • PHPMAILER_USERNAME=your-email@gmail.com"
echo "  • PHPMAILER_PASSWORD=<your-app-password>"
echo "  • PHPMAILER_ENCRYPTION=tls"
echo ""
echo "See RENDER_SETUP.md for detailed configuration"

echo ""
echo -e "${BLUE}Step 6: Deployment Steps${NC}"
echo "================================"
echo ""
echo "1. Ensure all code is committed to main branch:"
echo "   git add ."
echo "   git commit -m 'Prepare for Render deployment'"
echo "   git push origin main"
echo ""
echo "2. Go to https://render.com and create account"
echo ""
echo "3. Create PostgreSQL database:"
echo "   Dashboard → + New → PostgreSQL"
echo ""
echo "4. Create Web Service:"
echo "   Dashboard → + New → Web Service"
echo "   - Connect your GitHub repository"
echo "   - Render will auto-detect render.yaml"
echo "   - Add environment variables (from Step 5)"
echo "   - Click Deploy"
echo ""
echo "5. After deployment, run migrations in Render Shell:"
echo "   php artisan migrate --force"
echo ""
echo "6. Access your app at: https://your-service-name.onrender.com"
echo ""

echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}Setup guide complete!${NC}"
echo -e "${GREEN}================================${NC}"
echo ""
echo "Next steps:"
echo "1. Review RENDER_SETUP.md for detailed configuration"
echo "2. Set up your Render account and database"
echo "3. Deploy your application"
echo "4. Monitor logs in Render dashboard"
echo ""
echo "For help, see:"
echo "  • RENDER_SETUP.md - Render deployment guide"
echo "  • SECURITY.md - Security configuration"
echo "  • DEPLOYMENT.md - General deployment checklist"
echo ""
